### ISSUE TITLE
Remove all Catena-X (NG) references

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/tractus-x-umbrella#119]
This issue tracks the removal of all occurrences of `CatenaX-ng` in this repository as part of the broader goal to deprecate this organization.

- [x] Search for `Catena-X (NG)` in code, configuration, and documentation.
- [x] Remove or adapt references accordingly.
- [x] Close this issue once zero references remain.

Use this query to track your progress (overall): [GitHub Search Query](https://github.com/search?q=repo%3A[RepoName]+catenax-ng&type=code)

[This](https://github.com/search?q=org%3Aeclipse-tractusx+catenax-ng+repo%3Aeclipse-tractusx%2Ftractus-x-umbrella&type=code) query should display only results in related repository

Work summarized in https://github.com/eclipse-tractusx/sig-release/issues/838

**Comment by evegufy** [comment]
Only mentioned in docs https://github.com/search?q=repo%3Aeclipse-tractusx%2Ftractus-x-umbrella%20catenax-ng&type=code
