### ISSUE TITLE
Update IAM (Keycloak instances) to seed URLs, clients secrets, etc. dynamically

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/tractus-x-umbrella#126]
### Description

Update IAM (Keycloak instances) to set URLs, clients secrets, etc. dynamically
Option enabled with https://github.com/eclipse-tractusx/sig-release/issues/578

Version to be implemented is 4.0.0-alpha.x - this version is compatible with the R24.08 even though the IAM version for R24.08 was 3.0.1

**Comment by matbmoser** [comment]
Mikel and Carlos will take this over

**Comment by evegufy** [comment]
Done
