### ISSUE TITLE
SSI DIM Wallet Stub | Seed test data

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/tractus-x-umbrella#129]
### Description

In order to enable the [data exchange](https://github.com/eclipse-tractusx/tractus-x-umbrella/tree/umbrella-1.0.0/charts/umbrella#data-exchange), test data (wallets, credentials?, technical users) should be seeded into the SSI DIM Wallet Stub.

Before [R24.05 and the change to the DIM wallet](https://github.com/eclipse-tractusx/tractus-x-umbrella/tree/umbrella-1.0.0/charts/umbrella#note-for-r2405), this was taken care of by:
https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/umbrella-0.17.1/charts/umbrella/templates/post-install-miw-setup.yaml and https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/umbrella-0.17.1/concept/seeds-overall-data.md#centralidp-service-accounts-for-edc---miw-test-data

### Additional Information

Relates to https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/122

**Comment by evegufy** [comment]
Not needed because wallet stub always provides needed response without seeded test data.

**Comment by matbmoser** [comment]
We need to check if its working with the image

**Comment by evegufy** [comment]
As already commented https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/129#issuecomment-2426083633, it is not needed
