### ISSUE TITLE
Update discovery services to R24.08 (currently 0.2.2)

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/tractus-x-umbrella#136]
## Description 

Update the discovery services 0.3.1 - Helm version.
- Discovery Finder - 0.3.1
- BPN Discovery - 0.3.1

**Comment by tunacicek** [comment]
PR created:
https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/148

**Comment by evegufy** [comment]
https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/160
