### ISSUE TITLE
Update the Umbrella README

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/tractus-x-umbrella#151]
## Tasks:

- Update main readme from umbrella

**Comment by evegufy** [comment]
[Umbrella README.md](https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/umbrella-1.1.0/charts/umbrella/README.md) should be updated to reflect the latest addition of the SSI DIM Wallet Stub (once https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/125 is merged). Especially in this sections:
- https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/umbrella-1.1.0/charts/umbrella/README.md#note-for-r2405
- https://github.com/eclipse-tractusx/tractus-x-umbrella/blob/umbrella-1.1.0/charts/umbrella/README.md#data-exchange

As well as the postman collection with example requests for the data exchange should be added to the repo, in a `/docs/api/postman` directory. Please also add a docs/README.md (example [here](https://github.com/eclipse-tractusx/ssi-authority-schema-registry/blob/main/docs/README.md)) shortly describing that the directory contains example requests for the data exchange.
