### ISSUE TITLE
Enable EDC Discovery from Portal or Mocked

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/tractus-x-umbrella#167]
### Description

We need the EDC Discovery working with the same interface as defined in the portal.

Problem: We have no EDC registered in the portal, now how do we do it?

Proposals:
- We can deploy a [wiremock](https://wiremock.org/#opensource). -> The "easy way"
- Can we seed the portal database with the configured EDCs? -> The maybe hard way

Reason:

- DPP needs it
- IRS needs it

**Comment by matbmoser** [comment]
@evegufy can you support us on that? What do you think is the best way?

**Comment by kss682** [comment]
Hello @evegufy , 
When trying to seed the data there , the way it is configured in [here](https://github.com/eclipse-tractusx/portal/blob/main/charts/portal/templates/job-backend-portal-migrations.yaml#L129) and the way the umbrella helm is configured is different. 
`.Values.backend` in the portal helm and `.Values.portal.backend`

**Comment by kss682** [comment]
Hello @evegufy , 
When trying to seed the test data into the db, the job yaml [here](https://github.com/eclipse-tractusx/portal/blob/main/charts/portal/templates/job-backend-portal-migrations.yaml#L129) is configured to read from `.Values.backend` but our umbrella helm is configured on `.Values.portal.backend`.

**Comment by CDiezRodriguez** [comment]
Hi @evegufy,
Verified with PR #172 that seeding connectors into the portal works.

**Comment by evegufy** [comment]
> Hello @evegufy , When trying to seed the test data into the db, the job yaml [here](https://github.com/eclipse-tractusx/portal/blob/main/charts/portal/templates/job-backend-portal-migrations.yaml#L129) is configured to read from `.Values.backend` but our umbrella helm is configured on `.Values.portal.backend`.

Hi @kss682 first I thought you meant there was a bug in the portal chart for v2.2.0, but that's not you meant. Yes, sure, the example file which I linked exists in the context of the portal chart so `.Values.backend` is correct, if it's now supposed to be used in the context of the umbrella you need to introduce the according node `.Values.portal.backend`
